### ISSUE TITLE
mathjax link to equation

### ISSUE THREAD

**Issue by szcf-weiya** [szcf-weiya/ESL-CN#173]
sometimes the link locates a wrong position, for example, `(3.65)` and `(3.66)`, as shown in the following gif,
https://esl.hohoweiya.xyz/03-Linear-Methods-for-Regression/3.7-Multiple-Outcome-Shrinkage-and-Selection/index.html#mjx-eqn-3.66
![Peek 2021-01-06 20-54](https://user-images.githubusercontent.com/13688320/103770698-66b32b80-5061-11eb-91db-0f0a7ee5ec29.gif)

**Comment by szcf-weiya** [comment]
also reported in http://disq.us/p/2e8ldh3

**Comment by szcf-weiya** [comment]
## method 1 (not proper)
use `padding-top` and `margin-top` (https://www.cnblogs.com/shenjp/p/11088344.html), and the results is
![image](https://user-images.githubusercontent.com/13688320/103845095-4e312880-50d6-11eb-8b98-db339dab3720.png)

## method 2 (not proper)
https://www.cnblogs.com/shenjp/p/11088344.html
```css
.mjx-mtd:target {
  padding-top: 50px;  
}
```
![image](https://user-images.githubusercontent.com/13688320/103845896-fb587080-50d7-11eb-99a4-68d496329aec.png)

## method 3 (not work)
https://stackoverflow.com/questions/10732690/offsetting-an-html-anchor-to-adjust-for-fixed-header
```css
:target::before {
    content: '';
    display: block;
    height:      180px;
    margin-top: -180px;
}
```
![image](https://user-images.githubusercontent.com/13688320/103845727-9a309d00-50d7-11eb-8222-3c60b91b95e1.png)
